"""document upload

Revision ID: 2457ed08a69f
Revises: 5868996d8dc3
Create Date: 2025-03-08 19:57:35.896838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2457ed08a69f'
down_revision = '5868996d8dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blob_path', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('document_uploaded_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('vector_id')
        batch_op.drop_column('file_type')
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vector_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('document_uploaded_by_fkey', 'user', ['uploaded_by'], ['id'])
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('user_id')
        batch_op.drop_column('blob_path')

    # ### end Alembic commands ###
