"""Add user relationship to AuditLog

Revision ID: 5868996d8dc3
Revises: 
Create Date: 2025-03-08 14:02:12.012015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5868996d8dc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
